module:
    hugoVersion:
        extended: true
        min: "0.87.0"
baseURL: https://thefrenchghosty.me/
title: TheFrenchGhosty
keywords: TheFrenchGhosty
description: TheFrenchGhosty's personal website
paginate: 10
# hasCJKLanguage: true
languageCode: 'en-us'
# theme: # "hugo-theme-onelou"
params:
  # opengraph:
  #   github: 'https://github.com/jyygithub'
  #   gitee: 'https://gitee.com/'
  #   csdn: 'https://blog.csdn.net/'
  #   juejin: 'https://juejin.cn/'
  #   jianshu: 'https://www.jianshu.com/'
  #   twitter: 'https://twitter.com'
  #   facebook: 'https://facebook.com'
  footer:
    hidePowered: false # Powered by Hugo & theme OneLou
    # beian: # ICP备案号
    # gongan:
    #   # code: 公安备案号XXXX
    #   # txt: 京公网安备XXXX号
    since: 2022
    copyright: TheFrenchGhosty
  prefix:
    h2: "※ "
    h3: "✧ "
menu:
  navs:
    - name: Projects
      params:
        img: /img/code-slash.png
      url: /projects
      weight: 1
    - name: Wiki
      params:
        img: /img/book.png
      url: https://wiki.thefrenchghosty.me/
      weight: 2
    - name: GitHub
      params:
        img: /img/logo-github.png
      url: https://github.com/TheFrenchGhosty
      weight: 3
    - name: Contact
      params:
        img: /img/mail.png
      url: /contact
      weight: 4
    # - name: Blog
    #   params:
    #     img: /img/logo1.png
    #   url: /post/
    #   weight: 2
    # - name: Note
    #   params:
    #     img: /img/logo2.png
    #   weight: 2
    #   url: /note/
    # - name: Projects
    #   params:
    #     img: /img/logo2.png
    #   url: /projects/
    #   weight: 2
    # - name: About
    #   params:
    #     img: /img/logo3.png
    #   url: /about
    #   weight: 3
    # - name: 404
    #   params:
    #     img: /img/logo3.png
    #   url: /404.html
    #   weight: 4
