version: '3.0'

services:

  thefrenchghosty:
    container_name: thefrenchghosty
    image: quay.io/thefrenchghosty/thefrenchghosty:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:20010:80"
