baseURL = 'https://thefrenchghosty.me/'
locale = 'fr-fr'
title = 'TheFrenchGhosty'
theme = 'celadon'
enableRobotsTXT = true
[pagination]
  pagerSize = 10

keywords = 'TheFrenchGhosty'
description = "Le site web de TheFrenchGhosty"

[params.nav_external]
  blog = "https://blog.thefrenchghosty.me/"
  wiki = "https://wiki.thefrenchghosty.me/"
  github = "https://github.com/TheFrenchGhosty"

[params.homepage]
  sections = ["hero", "projects", "donate", "contact", "gpg"]

  [params.homepage.hero]
    enable = true
    layout = "hero"
    title = "About"
    showInMenu = false

  [params.homepage.projects]
    enable = true
    layout = "cards"
    title = "Projets"
    limit = 100

  [params.homepage.contact]
    enable = true
    layout = "content"
    title = "Contact"
    path = "/contact"

  [params.homepage.gpg]
    enable = true
    layout = "content"
    title = "GPG"
    path = "/gpg"

  [params.homepage.donate]
    enable = true
    layout = "content"
    title = "Donation"
    path = "/donate"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        enableInShortcodes = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [
            ["\\[", "\\]"],
            ["$$", "$$"]
          ]
          inline = [
            ["\\(", "\\)"],
            ["$", "$"]
          ]
  [markup.highlight]
    style = "friendly"
    noClasses = false
    lineNos = true
    guessSyntax = true

[[cascade]]
  layout = "single"
  [cascade.target]
    path = "/**"
    kind = "page"
